/**
 * ABI loader - reads ABIs from compiled Hardhat artifacts
 * Single source of truth: artifacts are generated by `npx hardhat compile`
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Artifact paths relative to project root
const ARTIFACTS_DIR = path.join(__dirname, "../../artifacts/contracts");

const ARTIFACT_PATHS = {
  TruthEngine: "TruthEngine/TruthEngine.sol/TruthEngine.json",
  OptimisticResolver: "resolvers/OptimisticResolver.sol/OptimisticResolver.json",
  SimpleTruthKeeper: "SimpleTruthKeeper.sol/SimpleTruthKeeper.json",
  PythPriceResolver: "resolvers/PythPriceResolver.sol/PythPriceResolver.json",
} as const;

type ContractName = keyof typeof ARTIFACT_PATHS;

// Cache loaded ABIs
const abiCache: Record<string, readonly unknown[]> = {};

/**
 * Load ABI from compiled artifact
 */
export function loadAbi(contractName: ContractName): readonly unknown[] {
  if (abiCache[contractName]) {
    return abiCache[contractName];
  }

  const artifactPath = path.join(ARTIFACTS_DIR, ARTIFACT_PATHS[contractName]);

  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `Artifact not found: ${artifactPath}\n` +
      `Run 'npx hardhat compile' to generate artifacts.`
    );
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  abiCache[contractName] = artifact.abi;

  return artifact.abi;
}

// Lazy-loaded ABIs (load on first access)
export const getRegistryAbi = () => loadAbi("TruthEngine");
export const getResolverAbi = () => loadAbi("OptimisticResolver");
export const getTruthKeeperAbi = () => loadAbi("SimpleTruthKeeper");
export const getPythResolverAbi = () => loadAbi("PythPriceResolver");

// State names for display (matches TOCState enum in TOCTypes.sol)
export const STATE_NAMES = [
  "NONE",             // 0
  "PENDING",          // 1
  "REJECTED",         // 2
  "ACTIVE",           // 3
  "RESOLVING",        // 4
  "DISPUTED_ROUND_1", // 5
  "DISPUTED_ROUND_2", // 6
  "RESOLVED",         // 7
  "CANCELLED",        // 8
];

// Native ETH address
export const ETH_ADDRESS = "0x0000000000000000000000000000000000000000" as const;
